version: '3.5'

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./vol_path:/var/lib/postgresql/data
    

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

  strategy_long_before_listing:
    build:
      dockerfile: ./StrategyLongBeforeListing/Dockerfile
    volumes:
      - ./StrategyLongBeforeListing:/app
    depends_on:
      - tickers_db_long_before_listing

  parser_long_before_listing:
    build:
      dockerfile: ./Parsers/Dockerfile
    volumes:
      - ./Parsers:/app
    depends_on:
      - database

  tickers_db_long_before_listing:
    build:
      dockerfile: ./TickerOnExchangesDatabase/Dockerfile
    volumes:
      - ./TickerOnExchangesDatabase:/app
    depends_on:
      - parser_long_before_listing



